name: CI
on: [pull_request]

jobs:
  ci:
    uses: forbiddenlink/.github/.github/workflows/ci-nextjs.yml@aa632ea70d0bef6aa71bc508753543a873c6a953 # main
  security:
    uses: forbiddenlink/.github/.github/workflows/security.yml@aa632ea70d0bef6aa71bc508753543a873c6a953 # main
