name: CI
on: [pull_request]

jobs:
  ci:
    uses: forbiddenlink/.github/.github/workflows/ci-nextjs.yml@a4fb9679dfb679801b7d1949b24bc654b397c691 # main
  security:
    uses: forbiddenlink/.github/.github/workflows/security.yml@a4fb9679dfb679801b7d1949b24bc654b397c691 # main
